CREATE TABLE `inventario` (
  `id_inventario` integer PRIMARY KEY,
  `id_tienda` integer,
  `id_sucursales` integer,
  `id_producto` integer,
  `inventario` integer,
  `pedido` integer,
  `stock` integer,
  `stock_minimo` integer,
  `variacion` integer,
  `fecha` timestamp DEFAULT (now()),
  `latitud` integer,
  `longitud` integer
);

CREATE TABLE `tiendas` (
  `id_tienda` integer PRIMARY KEY,
  `nombre` varchar(255),
  `id_sucursales` integer
);

CREATE TABLE `sucursales` (
  `id_sucursales` integer PRIMARY KEY,
  `nombre` varchar(255),
  `id_producto` integer
);

CREATE TABLE `productos` (
  `id_producto` integer PRIMARY KEY,
  `nombre` varchar(255)
);

CREATE TABLE `estados` (
  `id_estados` integer PRIMARY KEY
);

CREATE TABLE `catch` (
  `id_catch` integer PRIMARY KEY,
  `id_estados` integer,
  `fecha` timestamp DEFAULT (now()),
  `latitud` integer,
  `longitud` integer
);

ALTER TABLE `sucursales` ADD FOREIGN KEY (`id_sucursales`) REFERENCES `tiendas` (`id_tienda`);

CREATE TABLE `sucursales_productos` (
  `sucursales_id_producto` integer,
  `productos_id_producto` integer,
  PRIMARY KEY (`sucursales_id_producto`, `productos_id_producto`)
);

ALTER TABLE `sucursales_productos` ADD FOREIGN KEY (`sucursales_id_producto`) REFERENCES `sucursales` (`id_producto`);

ALTER TABLE `sucursales_productos` ADD FOREIGN KEY (`productos_id_producto`) REFERENCES `productos` (`id_producto`);


ALTER TABLE `estados` ADD FOREIGN KEY (`id_estados`) REFERENCES `catch` (`id_catch`);

ALTER TABLE `catch` ADD FOREIGN KEY (`fecha`) REFERENCES `inventario` (`fecha`);

ALTER TABLE `inventario` ADD FOREIGN KEY (`stock_minimo`) REFERENCES `tiendas` (`id_tienda`);



CREATE TABLE `sucursales` (
  `id_sucursales` INT PRIMARY KEY AUTO_INCREMENT,
  `nombre` varchar(30) ,
  `correo` varchar(50)  
) 


tiendas


FRANCO SUPERMERCADOS 
EMMEL 
LAMBRAMANI 
KOSTO TRISTAN 
KOSTO MAYORISTA 


SUPERMERCADOS PERUANOS 
PLAZA VEA EJERCITO 
PLAZA VEA MARINA 


HIPERMERCADOS TOTTUS
TOTTUS EJERCITO 
TOTTUS PORONGOCHE 
TOTTUS PARRA 


CENCOSUD RETAIL
METRO AVIACION 
METRO EJERCITO 
METRO LAMBRAMANI  
METRO HUNTER 


REPRESENTACIONES INTERNACIONALES - EL SUPER
SUPER PIEROLA
SUPER PORTAL 




CREATE TABLE `tiendas` (
  `id_tienda` integer PRIMARY KEY AUTO_INCREMENT,
  `nombre` varchar(50),
  `id_sucursales` integer
);

FRANCO SUPERMERCADOS 
SUPERMERCADOS PERUANOS
HIPERMERCADOS TOTTUS
CENCOSUD RETAIL
REPRESENTACIONES INTERNACIONALES - EL SUPER

CREATE TABLE `sucursales` (
  `id_sucursales` integer PRIMARY KEY AUTO_INCREMENT,
  `nombre` varchar(50),
);
EMMEL 
LAMBRAMANI 
KOSTO TRISTAN 
KOSTO MAYORISTA 
PLAZA VEA EJERCITO 
PLAZA VEA MARINA
TOTTUS EJERCITO 
TOTTUS PORONGOCHE 
TOTTUS PARRA 
METRO AVIACION 
METRO EJERCITO 
METRO LAMBRAMANI  
METRO HUNTER 
SUPER PIEROLA
SUPER PORTAL 

CREATE TABLE `productos` (
  `id_producto` integer PRIMARY KEY,
  `nombre` varchar(255)
);

         EMMEL 
CANELA MOLIDA FRASCO X 50 GRS
COMINO MOLIDO FRASCO X 50 GRS
PIMIENTA NEGRA MOLIDA FRASCO X 50 GRS
TUCO SAZON SALSA FRASCO X 70 GRS
SAZ.COMPL C/AJI SIN PICANTE FRASCO X 70 GRS
AJI COL.PANCA PICANTE FRASCO X 70 GRS
KION MOLIDO FRASCO X 50 GRS
SAL DE AJOS MOLIDO FRASCO X 50 GRS
PALILLO BATAN FRASCO X 70 GRS
OREGANO MOLIDO FRASCO X 25 GRS
AJI PAPRIKA PIMENTON FRASCO X 50 GRS
SAZ. EL VERDE FRASCO X 50 GRS
CURRY MOLIDO BATAN FRASCO X 50 GRS
PIMIENTA BLANCA MOLIDA BATAN FRASCO X 50 GRS


SAZONADOR COMPL. GIGANTE X 2 SBS   
COMINO BATAN GIGANTE X 2 SBS
PIMIENTA BATAN GIGANTE X 2 SBS 
PALILLO MOLIDO BATAN GIG. X 2 SBS     
TUCO SAZON SALSA GIGANTE X 2 SBS
AJO MOLIDO BATAN GIGANTE X 2 SBS 
CANELA MOLIDA BATAN X 2 SBS 
EL VERDE BATAN GIGANTE X 2 
OREGANO MOLIDO X 2 SBS 
KION MOLIDO X 2 SBS 
AJI PANCA FRESCO BATAN  X 3 SBS 
AJI AMARILLO FRESCO BATAN  X 3 SBS 
AJO FRESCO BATAN  X 3 SBS 
CULANTRO FRESCO BATAN  X 3 SBS 
COMINO  X 250 GRS 
AJO  X 250 GRS 
PMIENTA X 250 GRS  
OREGANO X  250 GRS 
SAZONADOR X 250 GRS  
PALILLO X 250 GRS  
SAL PARRILLERA RES FRASCO X 225 GRS  
SAL PARRILLERA POLLO  FRASCO X 215 GRS  
SAL PARRILLERA CERDO FRASCO X 220 GRS  
- AJI AMARILLO FRASCO X 70 GRS





          FRANCO

CANELA MOLIDA FRASCO X 50 GRS
COMINO MOLIDO FRASCO X 50 GRS
PIMIENTA NEGRA MOLIDA FRASCO X 50 GRS
TUCO SAZON SALSA FRASCO X 70 GRS
SAZ.COMPL C/AJI SIN PICANTE FRASCO X 70 GRS
AJI COL.PANCA PICANTE FRASCO X 70 GRS
KION MOLIDO FRASCO X 50 GRS
SAL DE AJOS MOLIDO FRASCO X 50 GRS
PALILLO BATAN FRASCO X 70 GRS
OREGANO MOLIDO FRASCO X 25 GRS
AJI PAPRIKA PIMENTON FRASCO X 50 GRS
SAZ. EL VERDE FRASCO X 50 GRS
CURRY MOLIDO BATAN FRASCO X 50 GRS
PIMIENTA BLANCA MOLIDA BATAN FRASCO X 50 GRS
SAZONADOR COMPL. GIGANTE X 2 SBS 
COMINO BATAN GIGANTE X 2 SBS
PIMIENTA BATAN GIGANTE X 2 SBS 
PALILLO MOLIDO BATAN GIG. X 2 SBS  
TUCO SAZON SALSA GIGANTE X 2 SBS
AJO MOLIDO BATAN GIGANTE X 2 SBS 
CANELA MOLIDA BATAN X 2 SBS 
EL VERDE BATAN GIGANTE X 2 
OREGANO MOLIDO X 2 SBS 
KION MOLIDO X 2 SBS 
AJI PANCA FRESCO BATAN  X 3 SBS 
AJI AMARILLO FRESCO BATAN  X 3 SBS 
AJO FRESCO BATAN  X 3 SBS 
CULANTRO FRESCO BATAN  X 3 SBS 
COMINO X 250 GRS 
AJO  X 250 GRS 
PMIENTA X 250 GRS  
OREGANO X  250 GRS 
SAZONADOR X 250 GRS  
PALILLO X 250 GRS
SAL PARRILLERA RES FRASCO X 225 GRS  
SAL PARRILLERA POLLO  FRASCO X 215 GRS  
SAL PARRILLERA CERDO FRASCO X 220 GRS 
-AJO MOLIDO BATAN GIGANTE X 8 SBS 
-CANELA MOLIDA BATAN X 8 SBS 


  


 


        KOSTO TRISTAN


CANELA MOLIDA FRASCO X 50 GRS
COMINO MOLIDO FRASCO X 50 GRS
PIMIENTA NEGRA MOLIDA FRASCO X 50 GRS
TUCO SAZON SALSA FRASCO X 70 GRS
SAZ.COMPL C/AJI SIN PICANTE FRASCO X 70 GRS
AJI COL.PANCA PICANTE FRASCO X 70 GRS
KION MOLIDO FRASCO X 50 GRS
SAL DE AJOS MOLIDO FRASCO X 50 GRS
PALILLO BATAN FRASCO X 70 GRS
OREGANO MOLIDO FRASCO X 25 GRS
AJI PAPRIKA PIMENTON FRASCO X 50 GRS
SAZ. EL VERDE FRASCO X 50 GRS
CURRY MOLIDO BATAN FRASCO X 50 GRS
PIMIENTA BLANCA MOLIDA BATAN FRASCO X 50 GRS
SAZONADOR COMPL. GIGANTE X 2 SBS                 
COMINO BATAN GIGANTE X 2 SBS
PIMIENTA BATAN GIGANTE X 2 SBS 
PALILLO MOLIDO BATAN GIG. X 2 SBS                         
TUCO SAZON SALSA GIGANTE X 2 SBS
AJO MOLIDO BATAN GIGANTE X 2 SBS 
CANELA MOLIDA BATAN X 2 SBS 
EL VERDE BATAN GIGANTE X 2 
OREGANO MOLIDO X 2 SBS 
KION MOLIDO X 2 SBS 
AJI PANCA FRESCO BATAN  X 3 SBS 
AJI AMARILLO FRESCO BATAN  X 3 SBS 
AJO FRESCO BATAN  X 3 SBS 
CULANTRO FRESCO BATAN  X 3 SBS 
COMINO X 250 GRS 
AJO  X 250 GRS 
PMIENTA X 250 GRS  
OREGANO X  250 GRS 
SAZONADOR X 250 GRS  
--PALILLO X 250 GRS
SAL PARRILLERA RES FRASCO X 225 GRS  
SAL PARRILLERA POLLO  FRASCO X 215 GRS  
SAL PARRILLERA CERDO FRASCO X 220 GRS  
-CANELA MOLIDA BATAN X 8 SBS 








          KOSTO MAYORISTA


-SAZ. COMPLETO  GIGANTE X 42 SBS
-PALILLO MOLIDO  GIGANTE X 42 SBS
-COMINO MOLIDO GIGANTE X 42 SBS
-PIMIENTA NEGRA MOLIDA GIGANTE X 42 SBS 
-TUCO SAZON SALSA GIGANTE X 42 SBS 
-AJO MOLIDO GIGANTE X 42 SBS 
-CANELA MOLIDA GIGANTE X 42 SBS
-EL VERDE GIGANTE X 42 SBS
-KION MOLIDO GIGANTE X 42 SBS 
-OREGANO SELECTO X 42 SBS

SAZONADOR COMPL. GIGANTE X 2 SBS                 
COMINO BATAN GIGANTE X 2 SBS
PIMIENTA BATAN GIGANTE X 2 SBS 
PALILLO MOLIDO BATAN GIG. X 2 SBS                         
TUCO SAZON SALSA GIGANTE X 2 SBS
AJO MOLIDO BATAN GIGANTE X 2 SBS 
CANELA MOLIDA BATAN X 2 SBS 
EL VERDE BATAN GIGANTE X 2 
OREGANO MOLIDO X 2 SBS 
KION MOLIDO X 2 SBS 
AJI PANCA FRESCO BATAN  X 3 SBS 
AJI AMARILLO FRESCO BATAN  X 3 SBS 
-AJO FRESCO BATAN  X 3 SBS 
CULANTRO FRESCO BATAN  X 3 SBS 
-SAZONADOR COMPLETO SIN PICANTE X 250 GR            
-COMINO MOLIDO X 250 GRS                            
-PIMIENTA MOLIDA  X 250 GR                          
-PALILLO MOLIDO X 250 GR                            
-AJO MOLIDO X 250 GR                                
-OREGANO MOLIDO X 250 GR                            
-SAZONADOR COMPLETO  X 500 GR                       
-COMINO MOLIDO X 500 GR                             
-PIMIENTA MOLIDA X 500 GR                           
-PALILLO MOLIDO X 500 GR                            
-AJO MOLIDO X 500 GR                                
-OREGANO MOLIDO X 500 GR                            
SAL PARRILLERA BATAN PARA RES FRASCO X 225 GR.
SAL PARRILLERA BATAN PARA POLLO FRASCO X 215 GR.
SAL PARRILLERA BATAN PARA CERDO FRASCO X 220 GR.



        SUPER PERUANOS
CANELA MOLIDA FRASCO X 50 GRS
SAZ.COMPL C/AJI SIN PICANTE FRASCO X 70 GRS
-SAZ. COMPLETO BATAN GIGANTE X 24 GRS
-COMINO MOLIDO BATAN GIGANTE X 13 GRS
-PIMIENTA NEGRA MOLIDA BATAN GIGANTE X 12 GRS
-TUCO SAZON SALSA BATAN GIGANTE X 20 GRS


       TOTTUS
CANELA MOLIDA FRASCO X 50 GRS
PIMIENTA NEGRA MOLIDA FRASCO X 50 GRS
TUCO SAZON SALSA FRASCO X 70 GRS
AJI COL.PANCA PICANTE FRASCO X 70 GRS
KION MOLIDO FRASCO X 50 GRS
CURRY MOLIDO BATAN FRASCO X 50 GRS
PIMIENTA BLANCA MOLIDA BATAN FRASCO X 50 GRS
*SAZ. COMPLETO BATAN GIGANTE X 24 GRS
PALILLO MOLIDO BATAN GIGANTE X 22 GRS
TUCO SAZON SALSA BATAN GIGANTE X 20 GRS
SAL DE AJOS MOLIDO BATAN GIGANTE X 16 GRS


        REINSAC-SUPER
CANELA MOLIDA FRASCO X 50 GRS
COMINO MOLIDO FRASCO X 50 GRS
PIMIENTA NEGRA MOLIDA FRASCO X 50 GRS
SAZ.COMPL C/AJI SIN PICANTE FRASCO X 70 GRS
KION MOLIDO FRASCO X 50 GRS
SAL DE AJOS MOLIDO FRASCO X 50 GRS
PALILLO BATAN FRASCO X 70 GRS
OREGANO MOLIDO FRASCO X 25 GRS
AJI AMARILLO FRASCO X 70 GRS
AJI PAPRIKA PIMENTON FRASCO X 50 GRS
CURRY MOLIDO BATAN FRASCO X 50 GRS
SAZ. EL VERDE FRASCO X 50 GRS
PIMIENTA BLANCA MOLIDA BATAN FRASCO X 50 GRS
SAZ. COMPLETO BATAN GIGANTE X 24 GRS
PALILLO MOLIDO BATAN GIGANTE X 22 GRS
COMINO MOLIDO BATAN GIGANTE X 13 GRS
PIMIENTA NEGRA MOLIDA BATAN GIGANTE X 12 GRS
TUCO SAZON SALSA BATAN GIGANTE X 20 GRS
SAL DE AJOS MOLIDO BATAN GIGANTE X 16 GRS
